README.md
default.json

Looking at the documentation more closely, I'm not entirely sure this is structured correctly. 
https://docs.renovatebot.com/config-presets/#example-configs
I guess I'm not that sure of the relationship between this file and the local repo's renovate.json - ie, what's the best way to allow teams to override defaults? Some guidance would be appreciated.

Add scheduling, codeowners, small readme update

---

.github/workflows/renovate-config-validator.yml
CODEOWNERS

This adds a `CODEOWNERS` file and makes use of `renovate-config-validator` to check that the configs we write are valid.

Codeowners and checks

---

README.md
default.json

This is important to run any upgrades against the latest version of the repository so that we run tests against up-to-date code and configuration.

feat: rebase stale PRs

---

README.md
default.json

This gets a reasonable amount of dependencies upgraded at least every week while not burying maintainers in PRs.

feat: limit number of PRs to 10 at a time

---

default.json

This moves from setting the options directly to using a template. It also removes the `prHourlyLimit` as this is the default config.

feat: improve PR number limits using only 1 template

---

default.json

The base template limits to two PRs per hour. As we have a limit of 10 in total, this can be lifted.

fix: override hourly limit from base template

---

README.md

The documentation is outdated as I forgot to change it with the last updates of the `default.json` file. By pointing directly to the description, this won’t be needed anymore.

docs: update documentation to point directly to the config file

---

default.json

"true" is not a valid value here. See https://docs.renovatebot.com/configuration-options/#semanticcommits

fix: correctly enable semanticCommits

---

default.json
docs/conda-environment.md

This adds a regex manager for the conda datasource which can be used as we don’t have a conda manager yet.

feat: add conda datasource with regex manager

---

default.json

This way the new renovate instance does not consider PRs of the old instance to be modified.

[CORE-984] Ignore commits of old renovate instance

---

default.json

This configures our default preset to include the workaround for the RedHat image versioning.
RedHat uses non-semver-compliant tags to version certain images, these are set to use the correct versioning syntax with this change.

feat: include RedHat image version workaround

---

default.json

Extends the regex pattern for conda environment files to:
* Allow either `.yml` or `.yaml` extensions
* Allow any characters between the word `environment` and the extension (e.g. `environment-dev.yaml`)
I placed the `.*` inside a capture group, which will not be used. I wouldn't have done that, but I noticed the `.` is not escaped.
Potentially the regex should instead be: `(^|/)environment.*\.ya?ml$`

feat: Extend conda env file regex

---

default.json

This will update the config to add the datasource to the beginning of the generated commit message. This is useful to make the PR titles include the data source, in cases where it could be ambiguous.
See this example below from my test project where both `pypi` and `conda` packages are in the same `environment.yml` file:
https://github.com/lembas-project/renovate-test/issues/1

feat: Add datasource to commit message for regex managed packages

---

.github/CODEOWNERS
.github/pull_request_template.md
default.json
docs/go-versions-makefile.md
docs/tflint-plugins.md

With this PR, we are
* widening ranges for `required_modules` blocks in terraform modules instead of replacing them.
* adding CODEOWNERS so that we assign reviews in this repo automatically
* adding a PR template for this repo
* adding multiple regexManagers for various file types that we reuse in many places (mainly terraform modules)

[CORE-2684] Additional regexManagers & config settings

---

default.json
docs/conda-environment.md
docs/tflint-plugins.md

This adds configuration to detect `# renovate:` comments to managers that previously only detected it **without** the colon.
It removes the old configuration from managers that were added in #39 since these are not in use anywhere.
Upstream-like regexManager comments are supported everywhere.

fix: use colons like upstream does

---

default.json

We are no longer using this user for renovate, it can therefore be removed.

chore: remove anaconda-renovate-bot from ignoredAuthors

---

default.json

Reverts anaconda/renovate-config#49.
We need to keep this for a while to ensure all old branches are "flushed". Since this piece of configuration does not hurt anyone, it does not matter if it stays for now.
Once all branches existing before 2023-08-01 are merged, we can remove this again.

Revert "chore: remove anaconda-renovate-bot from ignoredAuthors"

---

.github/workflows/renovate-config-validator.yml
README.md
terraformModule.json

This can be used with terraform modules to configure them specifically for the Anaconda best practices.
Configuration updates can be made at one central place for all modules.

feat: add preset for terraform modules

---

default.json
terraformModule.json

This removes config for tflint since this is captured by the **tflint-plugin** manager by now.
Also adds automerging for tflint-plugin manager to the terraform module preset.

chore: remove tflint config

---

default.json

With this change, updates to go modules will go much smoother:
- `gomodTidy` runs `go mod tidy`, which updates the `go.sum` file that contains the module hashes and cleans up the `go.mod` file
- `gomodUpdateImportPaths` updates import paths when module paths change, enabling major updates in one PR without manual intervention
Fewer manual touches needed for major updates of go modules.

feat: add go updating postUpdateOptions

---

default.json

This allows us to reference custom packages at `https://pypi.anaconda.org/<user>/simple` or another similar custom PyPI index. An example usage is shown below
```yaml
dependencies:
- python=3.9
- pip
- pip:
- requests==2.0
- my-internal-library==2.0.1
channels:
- defaults
```
This should just be an additive change, no unintended effects anticipated.
Here is the example regex testing:
[Regex101](https://regex101.com/r/8dVKZI/1)

feat: Add pattern to allow specifying custom PyPI URL

---

default.json

renovate somehow does not recognize "noon", use "12:00" instead.

fix: use 12:00 instead of noon

---

default.json

Docker container tags are not immutable versions, thus pinning them from e.g. node:14.15.1 to node:14.15.1@sha256:d938c1761e3afbae9242848ffbb95b9cc1cb0a24d889f8bd955204d347a7266e prevents "unnoticed" changes in containers.
This is especially relevant to all the external containers we use in helm charts or FROM statements, as somebody could replace a known good version with a bad one (supply chain attack).
The impact of the PR is from "FROM CONTAINER:$VERSION" statements in Dockerfiles to helm charts and values files.
It requires to also to make certain tags more explicit like from "debian:12-slim" to "debian:12.5-slim", to not have the digest changed without a version change. This can be done incrementally via the PRs that renovate anyways opens.
Renovate says "We recommend that you pin …

Enable Docker digest pinning

---

default.json

This was causing renovate to no longer identify previous commits as its own.  See-also https://anaconda.slack.com/archives/C010ZDG1ACB/p1721162321058809

Add 'old' style git user to gitIgnoredAuthors'

---

default.json

I think this is right.
See one example of the serverless v4 renovate bump in https://github.com/anaconda-distribution/rocket-platform/pull/1250
Or in https://github.com/anaconda/lambdas/pull/607

Pin Serverless major version to < 4.x due to license changes

---

default.json

The pin for `serverless < 4.0` was accidentally added to the `regexManagers` section instead of the `packageRules`. 
This PR resolves that issue and moves the `packageRules` to the bottom of the file to hopefully prevent similar issues in the future.
`serverless` is kept at versions `< 4.0`.

fix: serverless <4.0

---

default.json

See https://github.com/renovatebot/renovate/pull/30556 for details.
Fewer errors in the dependency dashboard.

fix: disable docker:pinDigests for ArgoCD

---

default.json

Digest pinning is not possible in helm chart dependencies, so we disable it, too.
This will be upstreamed once it's confirmed working.

fix: disable docker:pinDigests for helmv3

---

default.json

The current pinning pins from e.g. `- uses: actions/checkout@v3` to `- uses: actions/checkout@8e5e7... # v3`
And further updates from `- uses: actions/checkout@8e5e7... # v3` to `- uses: actions/checkout@0d6c329 # v3`
All those PRs would lack any changelog information as without knowing the Semver more information cannot be added to the PR description.
This could be manually fixed by somebody adding a full Semver and renovate would from then on start to do changes like: `- uses: actions/checkout@8e5e7... # v3.1.1` to `- uses: actions/checkout@0d6c329 # v3.1.2` with full changelog in the PR description.
This can be made easier by avoiding the manual step via `"helpers:pinGitHubActionDigestsToSemver"`
For more context see:
* https://github.com/renovatebot/renovate/discussions/21901
* …

Include full Semver as comment when pinning actions

---

default.json

This PR adds information about the fields relevant for renovate configuration to PRs.
With that information, it will become easier to write repository- and package-specific renovate configuration, since the relevant fields are known just by looking at a PR.

feat: add field details

---

.pre-commit-config.yaml
anaconda-installers.json
default.json
renovate.json
terraformModule.json

While renovate proposes migration PRs to the default configs like ./renovate.json in repos, it does not migrate the additional configs, which repos like this store. This can be achieved via the renovate pre-commit hook in [strict mode](https://docs.renovatebot.com/config-validation/#strict-mode) that detects not yet done migrations and also spits out how the config looks after migration.
This PR:
* enables the renovate-config-validator hook in strict mode for all renovate configs in the repo
* Incorporates the proposed migrations
* Formats all the configs for easier edits  / incorporating future migrations
Renovate should work as before.
Items like `customManagers:githubActionsVersions` become easier to look up in documentation as `regexManagers:githubActionsVersions` does not exist there …

Migrate renovate config(s) via pre-commit hook(s)
